In [45]:
import pandas as pd
import os
import matplotlib.pyplot as plt

In [60]:
df=pd.read_csv('cumulative_log_returns.csv')
cutoff=int(len(df)*0.5)
df1=df.iloc[:-cutoff]
df1.drop(columns={f'{df1.columns[0]}'},inplace=True)
df1

C:\Users\cheta\AppData\Local\Temp/ipykernel_28688/3519514320.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(columns={f'{df1.columns[0]}'},inplace=True)

,3MINDIA,AARTIIND,AAVAS,ABB,ABBOTINDIA,ABCAPITAL,ABFRL,ACC,ACE,ADANIENT,...,VTL,WELCORP,WELSPUNLIV,WHIRLPOOL,WIPRO,YESBANK,ZEEL,ZENSARTECH,ZFCVINDIA,ZYDUSLIFE
0,-0.001796,-0.016949,-0.022871,-0.066616,-0.003270,-0.015949,-0.012728,-0.018968,0.002181,-0.056457,...,-0.022189,-0.012569,-0.013649,-0.012125,-0.042266,-0.084156,-0.029540,-0.000644,0.001357,-0.034003
1,-0.030108,-0.021907,-0.005411,-0.102785,-0.027368,-0.052632,-0.004563,-0.047386,-0.064340,-0.109994,...,-0.028353,-0.039277,-0.049136,-0.025017,-0.059712,-0.032208,-0.061118,-0.010296,-0.004840,-0.051118
2,-0.041507,-0.055921,-0.006406,-0.072884,-0.020822,-0.044125,-0.037464,-0.014243,-0.074700,-0.095717,...,-0.028353,-0.044383,-0.049136,-0.030186,-0.064568,-0.050909,-0.069267,-0.023381,-0.001979,-0.025331
3,-0.035508,-0.080826,-0.004415,-0.083399,-0.004187,-0.048379,-0.056916,-0.025804,-0.061614,-0.107073,...,-0.028600,-0.061273,-0.032757,-0.024155,-0.059532,-0.033766,-0.066502,-0.021665,-0.002886,-0.035600
4,-0.047187,-0.086360,0.005610,-0.087201,-0.000532,-0.042531,-0.047070,-0.016957,-0.064885,-0.096690,...,-0.029832,-0.063629,-0.021838,-0.025176,-0.056655,-0.039481,-0.004657,-0.048048,-0.006443,-0.010041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,0.095142,1.211922,0.652028,0.490530,1.150601,0.266348,0.316282,0.382473,1.425845,10.207333,...,1.241371,0.307541,1.576888,0.097291,1.480216,-0.862857,-0.084546,0.930502,0.332600,1.032634
614,0.095405,1.261386,0.653256,0.498407,1.179945,0.273259,0.296350,0.391890,1.376772,10.341986,...,1.256164,0.338570,1.699727,0.113182,1.501079,-0.860260,-0.074360,1.048048,0.365828,1.032405
615,0.094557,1.271417,0.693587,0.511628,1.210382,0.315789,0.276897,0.399263,1.406761,10.128488,...,1.265533,0.346819,1.678799,0.105747,1.494784,-0.855584,-0.084546,1.154440,0.374381,1.081241
616,0.098810,1.246166,0.709985,0.517622,1.217857,0.286550,0.255283,0.399631,1.413850,9.988319,...,1.280325,0.329537,1.676979,0.115990,1.531655,-0.859221,-0.084255,1.130202,0.371535,1.126654
617,0.112577,1.295284,0.736739,0.516389,1.229719,0.317384,0.307637,0.433613,1.416576,10.073005,...,1.265779,0.334250,1.637853,0.114394,1.536151,-0.857662,-0.076397,1.141785,0.382712,1.143085

In [61]:
# First let us find out the correlation map of all the stocks present in the percentage_change.csv
# We are using spearman correlation to find the correlation between stocks
corr_matrix=df1.corr(method='spearman')
print(corr_matrix)

                          3MINDIA                   AARTIIND
3MINDIA                                   1.000000                 0.672124  \
AARTIIND                                  0.672124                 1.000000
AAVAS                                     0.851886                 0.718240
ABB                                       0.833993                 0.647656
ABBOTINDIA                                0.260228                 0.778194
...                                            ...                      ...
YESBANK                                  -0.389597                -0.812380
ZEEL                                      0.340353                -0.026567
ZENSARTECH                                0.778456                 0.765570
ZFCVINDIA                                 0.456737                 0.520752
ZYDUSLIFE                                 0.579875                 0.903612

                          AAVAS                    ABB
3MINDIA                                  0.851886                 0.833993  \
AARTIIND                                 0.718240                 0.647656
AAVAS                                    1.000000                 0.929081
ABB                                      0.929081                 1.000000
ABBOTINDIA                               0.349809                 0.274066
...                                           ...                      ...
YESBANK                                 -0.470683                -0.376952
ZEEL                                     0.416234                 0.492905
ZENSARTECH                               0.845477                 0.871757
ZFCVINDIA                                0.473908                 0.474301
ZYDUSLIFE                                0.645504                 0.545377

                          ABBOTINDIA               ABCAPITAL
3MINDIA                                  0.260228                 0.868217  \
AARTIIND                                 0.778194                 0.593203
AAVAS                                    0.349809                 0.880686
ABB                                      0.274066                 0.857252
ABBOTINDIA                               1.000000                 0.149129
...                                           ...                      ...
YESBANK                                 -0.778419                -0.324321
ZEEL                                    -0.253574                 0.409074
ZENSARTECH                               0.390461                 0.802343
ZFCVINDIA                                0.643615                 0.350506
ZYDUSLIFE                                0.706872                 0.564383

                          ABFRL                     ACC
3MINDIA                                   0.652528                 0.802689  \
AARTIIND                                  0.288203                 0.784909
AAVAS                                     0.779946                 0.871782
ABB                                       0.759417                 0.874929
ABBOTINDIA                                0.060121                 0.396223
...                                            ...                      ...
YESBANK                                  -0.051403                -0.610618
ZEEL                                      0.682803                 0.322763
ZENSARTECH                                0.533799                 0.951296
ZFCVINDIA                                 0.426285                 0.341436
ZYDUSLIFE                                 0.120040                 0.730994

                          ACE                     ADANIENT                ...
3MINDIA                                 0.846244                0.753665  ...  \
AARTIIND                                0.792402                0.914226  ...
AAVAS                                   0.921271                0.845268  ...
ABB                                     0.909108                0.764542  ...
ABBOTINDIA                              0.400963                0.628121  ...
...                                          ...                     ...  ...
YESBANK                                -0.549185               -0.776382  ...
ZEEL                                    0.356490                0.132897  ...
ZENSARTECH                              0.920724                0.820900  ...
ZFCVINDIA                               0.385302                0.458239  ...
ZYDUSLIFE                               0.731536                0.872513  ...

                          VTL                      WELCORP
3MINDIA                                  0.835911                 0.773043  \
AARTIIND                                 0.735004                 0.479555
AAVAS                                    0.959298                 0.818027
ABB                                      0.936909                 0.745065
ABBOTINDIA                               0.354357                 0.101714
...                                           ...                      ...
YESBANK                                 -0.453962                -0.177620
ZEEL                                     0.453770                 0.540565
ZENSARTECH                               0.886130                 0.593933
ZFCVINDIA                                0.457882                 0.351204
ZYDUSLIFE                                0.630759                 0.384760

                          WELSPUNLIV               WHIRLPOOL
3MINDIA                                  0.744830                  0.382366  \
AARTIIND                                 0.834654                  0.304093
AAVAS                                    0.822423                  0.458705
ABB                                      0.804461                  0.340303
ABBOTINDIA                               0.513798                  0.050357
...                                           ...                       ...
YESBANK                                 -0.702911                 -0.158631
ZEEL                                     0.296733                  0.112489
ZENSARTECH                               0.943278                  0.225366
ZFCVINDIA                                0.343436                  0.037219
ZYDUSLIFE                                0.778428                  0.362276

                          WIPRO                    YESBANK
3MINDIA                                  0.741016               -0.389597  \
AARTIIND                                 0.875671               -0.812380
AAVAS                                    0.796776               -0.470683
ABB                                      0.780178               -0.376952
ABBOTINDIA                               0.547080               -0.778419
...                                           ...                     ...
YESBANK                                 -0.758274                1.000000
ZEEL                                     0.217662                0.298712
ZENSARTECH                               0.925259               -0.565574
ZFCVINDIA                                0.391736               -0.432693
ZYDUSLIFE                                0.825002               -0.825214

                          ZEEL                    ZENSARTECH
3MINDIA                                 0.340353                 0.778456  \
AARTIIND                               -0.026567                 0.765570
AAVAS                                   0.416234                 0.845477
ABB                                     0.492905                 0.871757
ABBOTINDIA                             -0.253574                 0.390461
...                                          ...                      ...
YESBANK                                 0.298712                -0.565574
ZEEL                                    1.000000                 0.402043
ZENSARTECH                              0.402043                 1.000000
ZFCVINDIA                               0.055690                 0.333561
ZYDUSLIFE                              -0.217926                 0.687728

                          ZFCVINDIA                ZYDUSLIFE
3MINDIA                                  0.456737   0.579875
AARTIIND                                 0.520752   0.903612
AAVAS                                    0.473908   0.645504
ABB                                      0.474301   0.545377
ABBOTINDIA                               0.643615   0.706872
...                                           ...        ...
YESBANK                                 -0.432693  -0.825214
ZEEL                                     0.055690  -0.217926
ZENSARTECH                               0.333561   0.687728
ZFCVINDIA                                1.000000   0.397264
ZYDUSLIFE                                0.397264   1.000000

[404 rows x 404 columns]

In [48]:
corr_matrix.to_csv('corr_matrix.csv')

In [13]:
# df1=pd.read_csv('Adjusted_Close.csv')
# corr_matrix1=df1.corr(method='spearman')
# corr_matrix1.to_csv('corr_matrix1.csv')

In [73]:
df=pd.read_csv('corr_matrix.csv')
df.rename(columns={df.columns[0]:'stocks'},inplace=True)
df

,stocks,3MINDIA,AARTIIND,AAVAS,ABB,ABBOTINDIA,ABCAPITAL,ABFRL,ACC,ACE,...,VTL,WELCORP,WELSPUNLIV,WHIRLPOOL,WIPRO,YESBANK,ZEEL,ZENSARTECH,ZFCVINDIA,ZYDUSLIFE
0,3MINDIA,1.000000,0.672124,0.851886,0.833993,0.260228,0.868217,0.652528,0.802689,0.846244,...,0.835911,0.773043,0.744830,0.382366,0.741016,-0.389597,0.340353,0.778456,0.456737,0.579875
1,AARTIIND,0.672124,1.000000,0.718240,0.647656,0.778194,0.593203,0.288203,0.784909,0.792402,...,0.735004,0.479555,0.834654,0.304093,0.875671,-0.812380,-0.026567,0.765570,0.520752,0.903612
2,AAVAS,0.851886,0.718240,1.000000,0.929081,0.349809,0.880686,0.779946,0.871782,0.921271,...,0.959298,0.818027,0.822423,0.458705,0.796776,-0.470683,0.416234,0.845477,0.473908,0.645504
3,ABB,0.833993,0.647656,0.929081,1.000000,0.274066,0.857252,0.759417,0.874929,0.909108,...,0.936909,0.745065,0.804461,0.340303,0.780178,-0.376952,0.492905,0.871757,0.474301,0.545377
4,ABBOTINDIA,0.260228,0.778194,0.349809,0.274066,1.000000,0.149129,0.060121,0.396223,0.400963,...,0.354357,0.101714,0.513798,0.050357,0.547080,-0.778419,-0.253574,0.390461,0.643615,0.706872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,YESBANK,-0.389597,-0.812380,-0.470683,-0.376952,-0.778419,-0.324321,-0.051403,-0.610618,-0.549185,...,-0.453962,-0.177620,-0.702911,-0.158631,-0.758274,1.000000,0.298712,-0.565574,-0.432693,-0.825214
400,ZEEL,0.340353,-0.026567,0.416234,0.492905,-0.253574,0.409074,0.682803,0.322763,0.356490,...,0.453770,0.540565,0.296733,0.112489,0.217662,0.298712,1.000000,0.402043,0.055690,-0.217926
401,ZENSARTECH,0.778456,0.765570,0.845477,0.871757,0.390461,0.802343,0.533799,0.951296,0.920724,...,0.886130,0.593933,0.943278,0.225366,0.925259,-0.565574,0.402043,1.000000,0.333561,0.687728
402,ZFCVINDIA,0.456737,0.520752,0.473908,0.474301,0.643615,0.350506,0.426285,0.341436,0.385302,...,0.457882,0.351204,0.343436,0.037219,0.391736,-0.432693,0.055690,0.333561,1.000000,0.397264
403,ZYDUSLIFE,0.579875,0.903612,0.645504,0.545377,0.706872,0.564383,0.120040,0.730994,0.731536,...,0.630759,0.384760,0.778428,0.362276,0.825002,-0.825214,-0.217926,0.687728,0.397264,1.000000

In [74]:
df.set_index('stocks',inplace=True)
df

,3MINDIA,AARTIIND,AAVAS,ABB,ABBOTINDIA,ABCAPITAL,ABFRL,ACC,ACE,ADANIENT,...,VTL,WELCORP,WELSPUNLIV,WHIRLPOOL,WIPRO,YESBANK,ZEEL,ZENSARTECH,ZFCVINDIA,ZYDUSLIFE
stocks,,,,,,,,,,,,,,,,,,,,,
3MINDIA,1.000000,0.672124,0.851886,0.833993,0.260228,0.868217,0.652528,0.802689,0.846244,0.753665,...,0.835911,0.773043,0.744830,0.382366,0.741016,-0.389597,0.340353,0.778456,0.456737,0.579875
AARTIIND,0.672124,1.000000,0.718240,0.647656,0.778194,0.593203,0.288203,0.784909,0.792402,0.914226,...,0.735004,0.479555,0.834654,0.304093,0.875671,-0.812380,-0.026567,0.765570,0.520752,0.903612
AAVAS,0.851886,0.718240,1.000000,0.929081,0.349809,0.880686,0.779946,0.871782,0.921271,0.845268,...,0.959298,0.818027,0.822423,0.458705,0.796776,-0.470683,0.416234,0.845477,0.473908,0.645504
ABB,0.833993,0.647656,0.929081,1.000000,0.274066,0.857252,0.759417,0.874929,0.909108,0.764542,...,0.936909,0.745065,0.804461,0.340303,0.780178,-0.376952,0.492905,0.871757,0.474301,0.545377
ABBOTINDIA,0.260228,0.778194,0.349809,0.274066,1.000000,0.149129,0.060121,0.396223,0.400963,0.628121,...,0.354357,0.101714,0.513798,0.050357,0.547080,-0.778419,-0.253574,0.390461,0.643615,0.706872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YESBANK,-0.389597,-0.812380,-0.470683,-0.376952,-0.778419,-0.324321,-0.051403,-0.610618,-0.549185,-0.776382,...,-0.453962,-0.177620,-0.702911,-0.158631,-0.758274,1.000000,0.298712,-0.565574,-0.432693,-0.825214
ZEEL,0.340353,-0.026567,0.416234,0.492905,-0.253574,0.409074,0.682803,0.322763,0.356490,0.132897,...,0.453770,0.540565,0.296733,0.112489,0.217662,0.298712,1.000000,0.402043,0.055690,-0.217926
ZENSARTECH,0.778456,0.765570,0.845477,0.871757,0.390461,0.802343,0.533799,0.951296,0.920724,0.820900,...,0.886130,0.593933,0.943278,0.225366,0.925259,-0.565574,0.402043,1.000000,0.333561,0.687728
ZFCVINDIA,0.456737,0.520752,0.473908,0.474301,0.643615,0.350506,0.426285,0.341436,0.385302,0.458239,...,0.457882,0.351204,0.343436,0.037219,0.391736,-0.432693,0.055690,0.333561,1.000000,0.397264
ZYDUSLIFE,0.579875,0.903612,0.645504,0.545377,0.706872,0.564383,0.120040,0.730994,0.731536,0.872513,...,0.630759,0.384760,0.778428,0.362276,0.825002,-0.825214,-0.217926,0.687728,0.397264,1.000000

In [81]:
df.columns = df.columns.str.replace(' ', '')
df.index = df.index.str.replace(' ', '')

In [83]:
df

,3MINDIA,AARTIIND,AAVAS,ABB,ABBOTINDIA,ABCAPITAL,ABFRL,ACC,ACE,ADANIENT,...,VTL,WELCORP,WELSPUNLIV,WHIRLPOOL,WIPRO,YESBANK,ZEEL,ZENSARTECH,ZFCVINDIA,ZYDUSLIFE
stocks,,,,,,,,,,,,,,,,,,,,,
3MINDIA,1.000000,0.672124,0.851886,0.833993,0.260228,0.868217,0.652528,0.802689,0.846244,0.753665,...,0.835911,0.773043,0.744830,0.382366,0.741016,-0.389597,0.340353,0.778456,0.456737,0.579875
AARTIIND,0.672124,1.000000,0.718240,0.647656,0.778194,0.593203,0.288203,0.784909,0.792402,0.914226,...,0.735004,0.479555,0.834654,0.304093,0.875671,-0.812380,-0.026567,0.765570,0.520752,0.903612
AAVAS,0.851886,0.718240,1.000000,0.929081,0.349809,0.880686,0.779946,0.871782,0.921271,0.845268,...,0.959298,0.818027,0.822423,0.458705,0.796776,-0.470683,0.416234,0.845477,0.473908,0.645504
ABB,0.833993,0.647656,0.929081,1.000000,0.274066,0.857252,0.759417,0.874929,0.909108,0.764542,...,0.936909,0.745065,0.804461,0.340303,0.780178,-0.376952,0.492905,0.871757,0.474301,0.545377
ABBOTINDIA,0.260228,0.778194,0.349809,0.274066,1.000000,0.149129,0.060121,0.396223,0.400963,0.628121,...,0.354357,0.101714,0.513798,0.050357,0.547080,-0.778419,-0.253574,0.390461,0.643615,0.706872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YESBANK,-0.389597,-0.812380,-0.470683,-0.376952,-0.778419,-0.324321,-0.051403,-0.610618,-0.549185,-0.776382,...,-0.453962,-0.177620,-0.702911,-0.158631,-0.758274,1.000000,0.298712,-0.565574,-0.432693,-0.825214
ZEEL,0.340353,-0.026567,0.416234,0.492905,-0.253574,0.409074,0.682803,0.322763,0.356490,0.132897,...,0.453770,0.540565,0.296733,0.112489,0.217662,0.298712,1.000000,0.402043,0.055690,-0.217926
ZENSARTECH,0.778456,0.765570,0.845477,0.871757,0.390461,0.802343,0.533799,0.951296,0.920724,0.820900,...,0.886130,0.593933,0.943278,0.225366,0.925259,-0.565574,0.402043,1.000000,0.333561,0.687728
ZFCVINDIA,0.456737,0.520752,0.473908,0.474301,0.643615,0.350506,0.426285,0.341436,0.385302,0.458239,...,0.457882,0.351204,0.343436,0.037219,0.391736,-0.432693,0.055690,0.333561,1.000000,0.397264
ZYDUSLIFE,0.579875,0.903612,0.645504,0.545377,0.706872,0.564383,0.120040,0.730994,0.731536,0.872513,...,0.630759,0.384760,0.778428,0.362276,0.825002,-0.825214,-0.217926,0.687728,0.397264,1.000000

In [84]:
pairs_list=[]
for row_index, row in df.iterrows():
    for col_name in df.columns:
        if row[col_name] > 0.85 and row[col_name] < 0.9 and row_index!=col_name:
            if (row_index,col_name) not in pairs_list:
                pairs_list.append((col_name, row_index))

pairs_list

[('AAVAS', '3MINDIA'),
 ('ABCAPITAL', '3MINDIA'),
 ('ADANIPORTS', '3MINDIA'),
 ('ADANIPOWER', '3MINDIA'),
 ('BAJAJFINSV', '3MINDIA'),
 ('BEML', '3MINDIA'),
 ('BLUESTARCO', '3MINDIA'),
 ('CARBORUNIV', '3MINDIA'),
 ('CHOLAFIN', '3MINDIA'),
 ('CHOLAHLDNG', '3MINDIA'),
 ('ELECON', '3MINDIA'),
 ('GESHIP', '3MINDIA'),
 ('GSFC', '3MINDIA'),
 ('HINDCOPPER', '3MINDIA'),
 ('IDFC', '3MINDIA'),
 ('IIFL', '3MINDIA'),
 ('JKLAKSHMI', '3MINDIA'),
 ('KSB', '3MINDIA'),
 ('NATIONALUM', '3MINDIA'),
 ('NMDC', '3MINDIA'),
 ('PGHH', '3MINDIA'),
 ('QUESS', '3MINDIA'),
 ('RAMCOCEM', '3MINDIA'),
 ('SAIL', '3MINDIA'),
 ('SBIN', '3MINDIA'),
 ('SCHAEFFLER', '3MINDIA'),
 ('SHRIRAMFIN', '3MINDIA'),
 ('SKFINDIA', '3MINDIA'),
 ('SUNDARMFIN', '3MINDIA'),
 ('SUNDRMFAST', '3MINDIA'),
 ('TATAMOTORS', '3MINDIA'),
 ('TATAMTRDVR', '3MINDIA'),
 ('ALLCARGO', 'AARTIIND'),
 ('AMBUJACEM', 'AARTIIND'),
 ('ASAHIINDIA', 'AARTIIND'),
 ('ATGL', 'AARTIIND'),
 ('BIRLACORPN', 'AARTIIND'),
 ('CGCL', 'AARTIIND'),
 ('CHAMBLFERT', 'AARTIIND'),
 ('CROMPTON', 'AARTIIND'),
 ('ECLERX', 'AARTIIND'),
 ('ESCORTS', 'AARTIIND'),
 ('FSL', 'AARTIIND'),
 ('GAEL', 'AARTIIND'),
 ('GPIL', 'AARTIIND'),
 ('HAL', 'AARTIIND'),
 ('HINDUNILVR', 'AARTIIND'),
 ('HINDZINC', 'AARTIIND'),
 ('HONAUT', 'AARTIIND'),
 ('INDIAMART', 'AARTIIND'),
 ('INFY', 'AARTIIND'),
 ('INOXWIND', 'AARTIIND'),
 ('JBMA', 'AARTIIND'),
 ('JINDALSTEL', 'AARTIIND'),
 ('JSWSTEEL', 'AARTIIND'),
 ('KEC', 'AARTIIND'),
 ('LTTS', 'AARTIIND'),
 ('MPHASIS', 'AARTIIND'),
 ('NESTLEIND', 'AARTIIND'),
 ('NETWORK18', 'AARTIIND'),
 ('POLYCAB', 'AARTIIND'),
 ('RATNAMANI', 'AARTIIND'),
 ('REDINGTON', 'AARTIIND'),
 ('RENUKA', 'AARTIIND'),
 ('RTNINDIA', 'AARTIIND'),
 ('SAREGAMA', 'AARTIIND'),
 ('SONATSOFTW', 'AARTIIND'),
 ('SYNGENE', 'AARTIIND'),
 ('TATAINVEST', 'AARTIIND'),
 ('TCS', 'AARTIIND'),
 ('TECHM', 'AARTIIND'),
 ('TORNTPHARM', 'AARTIIND'),
 ('TRIDENT', 'AARTIIND'),
 ('TTML', 'AARTIIND'),
 ('VBL', 'AARTIIND'),
 ('WIPRO', 'AARTIIND'),
 ('ABCAPITAL', 'AAVAS'),
 ('ACC', 'AAVAS'),
 ('ADANIPORTS', 'AAVAS'),
 ('ADANIPOWER', 'AAVAS'),
 ('APOLLOTYRE', 'AAVAS'),
 ('BAJAJHLDNG', 'AAVAS'),
 ('BIRLACORPN', 'AAVAS'),
 ('BLUEDART', 'AAVAS'),
 ('CANFINHOME', 'AAVAS'),
 ('CENTURYPLY', 'AAVAS'),
 ('CGCL', 'AAVAS'),
 ('CIEINDIA', 'AAVAS'),
 ('CONCOR', 'AAVAS'),
 ('CROMPTON', 'AAVAS'),
 ('DCMSHRIRAM', 'AAVAS'),
 ('ELGIEQUIP', 'AAVAS'),
 ('ENDURANCE', 'AAVAS'),
 ('GAIL', 'AAVAS'),
 ('GESHIP', 'AAVAS'),
 ('GODREJIND', 'AAVAS'),
 ('GPPL', 'AAVAS'),
 ('GRAPHITE', 'AAVAS'),
 ('GSPL', 'AAVAS'),
 ('HBLPOWER', 'AAVAS'),
 ('HEG', 'AAVAS'),
 ('HFCL', 'AAVAS'),
 ('HINDCOPPER', 'AAVAS'),
 ('ICICIPRULI', 'AAVAS'),
 ('IDFCFIRSTB', 'AAVAS'),
 ('JAIBALAJI', 'AAVAS'),
 ('JBMA', 'AAVAS'),
 ('JKLAKSHMI', 'AAVAS'),
 ('JSWSTEEL', 'AAVAS'),
 ('KANSAINER', 'AAVAS'),
 ('KEC', 'AAVAS'),
 ('KPITTECH', 'AAVAS'),
 ('LT', 'AAVAS'),
 ('LTTS', 'AAVAS'),
 ('MHRIL', 'AAVAS'),
 ('MMTC', 'AAVAS'),
 ('MOTHERSON', 'AAVAS'),
 ('NAM-INDIA', 'AAVAS'),
 ('NMDC', 'AAVAS'),
 ('PCBL', 'AAVAS'),
 ('PGHH', 'AAVAS'),
 ('POLYCAB', 'AAVAS'),
 ('POONAWALLA', 'AAVAS'),
 ('POWERGRID', 'AAVAS'),
 ('PRSMJOHNSN', 'AAVAS'),
 ('RATNAMANI', 'AAVAS'),
 ('REDINGTON', 'AAVAS'),
 ('SAIL', 'AAVAS'),
 ('SBILIFE', 'AAVAS'),
 ('SONATSOFTW', 'AAVAS'),
 ('TATAINVEST', 'AAVAS'),
 ('TATAPOWER', 'AAVAS'),
 ('TATASTEEL', 'AAVAS'),
 ('TECHM', 'AAVAS'),
 ('TEJASNET', 'AAVAS'),
 ('THERMAX', 'AAVAS'),
 ('TITAGARH', 'AAVAS'),
 ('TRITURBINE', 'AAVAS'),
 ('TRIVENI', 'AAVAS'),
 ('TVSMOTOR', 'AAVAS'),
 ('UPL', 'AAVAS'),
 ('VBL', 'AAVAS'),
 ('ABCAPITAL', 'ABB'),
 ('ACC', 'ABB'),
 ('ADANIPORTS', 'ABB'),
 ('APARINDS', 'ABB'),
 ('APOLLOTYRE', 'ABB'),
 ('ASHOKLEY', 'ABB'),
 ('ASTRAL', 'ABB'),
 ('BALRAMCHIN', 'ABB'),
 ('BEL', 'ABB'),
 ('BHARATFORG', 'ABB'),
 ('BHEL', 'ABB'),
 ('BLUESTARCO', 'ABB'),
 ('CENTURYPLY', 'ABB'),
 ('CERA', 'ABB'),
 ('CHOLAFIN', 'ABB'),
 ('DALBHARAT', 'ABB'),
 ('FINPIPE', 'ABB'),
 ('FORTIS', 'ABB'),
 ('GMDCLTD', 'ABB'),
 ('GODREJPROP', 'ABB'),
 ('GRAPHITE', 'ABB'),
 ('GRASIM', 'ABB'),
 ('HAVELLS', 'ABB'),
 ('HBLPOWER', 'ABB'),
 ('HDFCBANK', 'ABB'),
 ('HEG', 'ABB'),
 ('HINDPETRO', 'ABB'),
 ('IDFCFIRSTB', 'ABB'),
 ('INDIGO', 'ABB'),
 ('JAIBALAJI', 'ABB'),
 ('JINDALSAW', 'ABB'),
 ('JKLAKSHMI', 'ABB'),
 ('KAJARIACER', 'ABB'),
 ('KNRCON', 'ABB'),
 ('KPITTECH', 'ABB'),
 ('KPRMILL', 'ABB'),
 ('NBCC', 'ABB'),
 ('NCC', 'ABB'),
 ('NMDC', 'ABB'),
 ('NTPC', 'ABB'),
 ('OIL', 'ABB'),
 ('PAGEIND', 'ABB'),
 ('PEL', 'ABB'),
 ('PHOENIXLTD', 'ABB'),
 ('PRSMJOHNSN', 'ABB'),
 ('RAMCOCEM', 'ABB'),
 ('RHIM', 'ABB'),
 ('RKFORGE', 'ABB'),
 ('SJVN', 'ABB'),
 ('SUNDARMFIN', 'ABB'),
 ('TATAMOTORS', 'ABB'),
 ('TATASTEEL', 'ABB'),
 ('TEJASNET', 'ABB'),
 ('TITAN', 'ABB'),
 ('UBL', 'ABB'),
 ('ULTRACEMCO', 'ABB'),
 ('UNOMINDA', 'ABB'),
 ('UPL', 'ABB'),
 ('VGUARD', 'ABB'),
 ('VOLTAS', 'ABB'),
 ('ZENSARTECH', 'ABB'),
 ('TORNTPHARM', 'ABBOTINDIA'),
 ('ADANIPORTS', 'ABCAPITAL'),
 ('ADANIPOWER', 'ABCAPITAL'),
 ('APOLLOTYRE', 'ABCAPITAL'),
 ('BAJAJFINSV', 'ABCAPITAL'),
 ('BALRAMCHIN', 'ABCAPITAL'),
 ('BEML', 'ABCAPITAL'),
 ('BLUESTARCO', 'ABCAPITAL'),
 ('BRIGADE', 'ABCAPITAL'),
 ('CARBORUNIV', 'ABCAPITAL'),
 ('CHOLAFIN', 'ABCAPITAL'),
 ('CHOLAHLDNG', 'ABCAPITAL'),
 ('COCHINSHIP', 'ABCAPITAL'),
 ('CUMMINSIND', 'ABCAPITAL'),
 ('DALBHARAT', 'ABCAPITAL'),
 ('DLF', 'ABCAPITAL'),
 ('ELECON', 'ABCAPITAL'),
 ('ELGIEQUIP', 'ABCAPITAL'),
 ('FINCABLES', 'ABCAPITAL'),
 ('GAIL', 'ABCAPITAL'),
 ('GESHIP', 'ABCAPITAL'),
 ('GODREJIND', 'ABCAPITAL'),
 ('GRINDWELL', 'ABCAPITAL'),
 ('GSFC', 'ABCAPITAL'),
 ('HEG', 'ABCAPITAL'),
 ('HINDALCO', 'ABCAPITAL'),
 ('HINDCOPPER', 'ABCAPITAL'),
 ('ICICIBANK', 'ABCAPITAL'),
 ('IIFL', 'ABCAPITAL'),
 ('JKPAPER', 'ABCAPITAL'),
 ('JSWENERGY', 'ABCAPITAL'),
 ('JUSTDIAL', 'ABCAPITAL'),
 ('KSB', 'ABCAPITAL'),
 ('MAHABANK', 'ABCAPITAL'),
 ('MAHLIFE', 'ABCAPITAL'),
 ('MINDACORP', 'ABCAPITAL'),
 ('MMTC', 'ABCAPITAL'),
 ('MOTHERSON', 'ABCAPITAL'),
 ('NATIONALUM', 'ABCAPITAL'),
 ('NBCC', 'ABCAPITAL'),
 ('NCC', 'ABCAPITAL'),
 ('NHPC', 'ABCAPITAL'),
 ('NMDC', 'ABCAPITAL'),
 ('PNCINFRA', 'ABCAPITAL'),
 ('POONAWALLA', 'ABCAPITAL'),
 ('PRAJIND', 'ABCAPITAL'),
 ('PRSMJOHNSN', 'ABCAPITAL'),
 ('QUESS', 'ABCAPITAL'),
 ('RAMCOCEM', 'ABCAPITAL'),
 ('RECLTD', 'ABCAPITAL'),
 ('RHIM', 'ABCAPITAL'),
 ('RVNL', 'ABCAPITAL'),
 ('SAIL', 'ABCAPITAL'),
 ('SBIN', 'ABCAPITAL'),
 ('SCHAEFFLER', 'ABCAPITAL'),
 ('SHRIRAMFIN', 'ABCAPITAL'),
 ('SJVN', 'ABCAPITAL'),
 ('SKFINDIA', 'ABCAPITAL'),
 ('SUNDRMFAST', 'ABCAPITAL'),
 ('TATAMOTORS', 'ABCAPITAL'),
 ('TATAMTRDVR', 'ABCAPITAL'),
 ('THERMAX', 'ABCAPITAL'),
 ('UPL', 'ABCAPITAL'),
 ('VEDL', 'ABCAPITAL'),
 ('VTL', 'ABCAPITAL'),
 ('INDHOTEL', 'ABFRL'),
 ('PHOENIXLTD', 'ABFRL'),
 ('PRESTIGE', 'ABFRL'),
 ('VIPIND', 'ABFRL'),
 ('ADANIENT', 'ACC'),
 ('ALLCARGO', 'ACC'),
 ('APLAPOLLO', 'ACC'),
 ('APOLLOHOSP', 'ACC'),
 ('ATGL', 'ACC'),
 ('BAJAJFINSV', 'ACC'),
 ('BAJFINANCE', 'ACC'),
 ('BALRAMCHIN', 'ACC'),
 ('BEL', 'ACC'),
 ('BEML', 'ACC'),
 ('BIRLACORPN', 'ACC'),
 ('BLS', 'ACC'),
 ('CANFINHOME', 'ACC'),
 ('CGCL', 'ACC'),
 ('CHOLAHLDNG', 'ACC'),
 ('CIEINDIA', 'ACC'),
 ('COFORGE', 'ACC'),
 ('CROMPTON', 'ACC'),
 ('DLF', 'ACC'),
 ('ECLERX', 'ACC'),
 ('FINCABLES', 'ACC'),
 ('FORTIS', 'ACC'),
 ('GAEL', 'ACC'),
 ('GAIL', 'ACC'),
 ('GODREJIND', 'ACC'),
 ('GPIL', 'ACC'),
 ('HCLTECH', 'ACC'),
 ('HINDZINC', 'ACC'),
 ('INDIGO', 'ACC'),
 ('INFY', 'ACC'),
 ('JBMA', 'ACC'),
 ('JSL', 'ACC'),
 ('JWL', 'ACC'),
 ('KANSAINER', 'ACC'),
 ('KEC', 'ACC'),
 ('LT', 'ACC'),
 ('M&M', 'ACC'),
 ('MAHLIFE', 'ACC'),
 ('MASTEK', 'ACC'),
 ('MOTHERSON', 'ACC'),
 ('NCC', 'ACC'),
 ('NHPC', 'ACC'),
 ('NMDC', 'ACC'),
 ('OBEROIRLTY', 'ACC'),
 ('PAGEIND', 'ACC'),
 ('PERSISTENT', 'ACC'),
 ('PFC', 'ACC'),
 ('PNCINFRA', 'ACC'),
 ('POONAWALLA', 'ACC'),
 ('QUESS', 'ACC'),
 ('RATNAMANI', 'ACC'),
 ('RECLTD', 'ACC'),
 ('RHIM', 'ACC'),
 ('RVNL', 'ACC'),
 ('SAIL', 'ACC'),
 ('SAREGAMA', 'ACC'),
 ('SBIN', 'ACC'),
 ('SCHAEFFLER', 'ACC'),
 ('SJVN', 'ACC'),
 ('SKFINDIA', 'ACC'),
 ('SOBHA', 'ACC'),
 ('SOLARINDS', 'ACC'),
 ('SUNDARMFIN', 'ACC'),
 ('SUNTV', 'ACC'),
 ('SUPREMEIND', 'ACC'),
 ('TATAMOTORS', 'ACC'),
 ('TCS', 'ACC'),
 ('THERMAX', 'ACC'),
 ('TIINDIA', 'ACC'),
 ('TRIDENT', 'ACC'),
 ('TTML', 'ACC'),
 ('TVSMOTOR', 'ACC'),
 ('UNOMINDA', 'ACC'),
 ('USHAMART', 'ACC'),
 ('VTL', 'ACC'),
 ('ADANIENT', 'ACE'),
 ('APLAPOLLO', 'ACE'),
 ('APOLLOHOSP', 'ACE'),
 ('ASIANPAINT', 'ACE'),
 ('ATGL', 'ACE'),
 ('BAJAJ-AUTO', 'ACE'),
 ('BLUESTARCO', 'ACE'),
 ('CEATLTD', 'ACE'),
 ('CGCL', 'ACE'),
 ('COFORGE', 'ACE'),
 ('ECLERX', 'ACE'),
 ('EICHERMOT', 'ACE'),
 ('FINCABLES', 'ACE'),
 ('FSL', 'ACE'),
 ('GAEL', 'ACE'),
 ('GAIL', 'ACE'),
 ('GESHIP', 'ACE'),
 ('GMRINFRA', 'ACE'),
 ('GODREJCP', 'ACE'),
 ('GODREJIND', 'ACE'),
 ('GRAPHITE', 'ACE'),
 ('HCLTECH', 'ACE'),
 ('HDFCLIFE', 'ACE'),
 ('HINDCOPPER', 'ACE'),
 ('HINDZINC', 'ACE'),
 ('HUDCO', 'ACE'),
 ('ICICIPRULI', 'ACE'),
 ('IIFL', 'ACE'),
 ('INDIGO', 'ACE'),
 ('INFY', 'ACE'),
 ('INOXWIND', 'ACE'),
 ('INTELLECT', 'ACE'),
 ('IOB', 'ACE'),
 ('JINDALSAW', 'ACE'),
 ('JINDALSTEL', 'ACE'),
 ('JKPAPER', 'ACE'),
 ('JSL', 'ACE'),
 ('JUSTDIAL', 'ACE'),
 ('JWL', 'ACE'),
 ('KEI', 'ACE'),
 ('KOTAKBANK', 'ACE'),
 ('LINDEINDIA', 'ACE'),
 ('M&M', 'ACE'),
 ('MAHABANK', 'ACE'),
 ('MARICO', 'ACE'),
 ('MASTEK', 'ACE'),
 ('MHRIL', 'ACE'),
 ('MINDACORP', 'ACE'),
 ('MMTC', 'ACE'),
 ('MPHASIS', 'ACE'),
 ('NCC', 'ACE'),
 ('NH', 'ACE'),
 ('OFSS', 'ACE'),
 ('PERSISTENT', 'ACE'),
 ('PGHH', 'ACE'),
 ('POLYCAB', 'ACE'),
 ('POONAWALLA', 'ACE'),
 ('RATNAMANI', 'ACE'),
 ('SAREGAMA', 'ACE'),
 ('SHREECEM', 'ACE'),
 ('SHRIRAMFIN', 'ACE'),
 ('SKFINDIA', 'ACE'),
 ('SOLARINDS', 'ACE'),
 ('SUPREMEIND', 'ACE'),
 ('TATACHEM', 'ACE'),
 ('TATAELXSI', 'ACE'),
 ('TCS', 'ACE'),
 ('THERMAX', 'ACE'),
 ('TIINDIA', 'ACE'),
 ('TRIDENT', 'ACE'),
 ('TRIVENI', 'ACE'),
 ('TVSMOTOR', 'ACE'),
 ('VBL', 'ACE'),
 ('WIPRO', 'ACE'),
 ('ADANIGREEN', 'ADANIENT'),
 ('AJANTPHARM', 'ADANIENT'),
 ('ALKEM', 'ADANIENT'),
 ('BAJAJ-AUTO', 'ADANIENT'),
 ('BALRAMCHIN', 'ADANIENT'),
 ('BEL', 'ADANIENT'),
 ('BLS', 'ADANIENT'),
 ('BRIGADE', 'ADANIENT'),
 ('BSE', 'ADANIENT'),
 ('CARBORUNIV', 'ADANIENT'),
 ('CEATLTD', 'ADANIENT'),
 ('CERA', 'ADANIENT'),
 ('CGPOWER', 'ADANIENT'),
 ('CHOLAFIN', 'ADANIENT'),
 ('CHOLAHLDNG', 'ADANIENT'),
 ('CIPLA', 'ADANIENT'),
 ('CYIENT', 'ADANIENT'),
 ('DLF', 'ADANIENT'),
 ('DMART', 'ADANIENT'),
 ('EICHERMOT', 'ADANIENT'),
 ('FACT', 'ADANIENT'),
 ('FSL', 'ADANIENT'),
 ('GNFC', 'ADANIENT'),
 ('GODREJCP', 'ADANIENT'),
 ('GODREJPROP', 'ADANIENT'),
 ('GRASIM', 'ADANIENT'),
 ('GRINDWELL', 'ADANIENT'),
 ('HAL', 'ADANIENT'),
 ('HAVELLS', 'ADANIENT'),
 ('HBLPOWER', 'ADANIENT'),
 ('HDFCBANK', 'ADANIENT'),
 ('HDFCLIFE', 'ADANIENT'),
 ('HINDALCO', 'ADANIENT'),
 ('HINDCOPPER', 'ADANIENT'),
 ('HINDZINC', 'ADANIENT'),
 ('HONAUT', 'ADANIENT'),
 ('ICICIBANK', 'ADANIENT'),
 ('IDFC', 'ADANIENT'),
 ('INDIAMART', 'ADANIENT'),
 ('INOXWIND', 'ADANIENT'),
 ('KANSAINER', 'ADANIENT'),
 ('M&M', 'ADANIENT'),
 ('MUTHOOTFIN', 'ADANIENT'),
 ('NETWORK18', 'ADANIENT'),
 ('NHPC', 'ADANIENT'),
 ('OFSS', 'ADANIENT'),
 ('RAMCOCEM', 'ADANIENT'),
 ('RENUKA', 'ADANIENT'),
 ('RHIM', 'ADANIENT'),
 ('RKFORGE', 'ADANIENT'),
 ('RTNINDIA', 'ADANIENT'),
 ('SAIL', 'ADANIENT'),
 ('SHREECEM', 'ADANIENT'),
 ('SPARC', 'ADANIENT'),
 ('STLTECH', 'ADANIENT'),
 ('SUNDRMFAST', 'ADANIENT'),
 ('SUNPHARMA', 'ADANIENT'),
 ('SUNTV', 'ADANIENT'),
 ('TATAMOTORS', 'ADANIENT'),
 ('TATAMTRDVR', 'ADANIENT'),
 ('TATAPOWER', 'ADANIENT'),
 ('TITAGARH', 'ADANIENT'),
 ('TTML', 'ADANIENT'),
 ('ULTRACEMCO', 'ADANIENT'),
 ('VAIBHAVGBL', 'ADANIENT'),
 ('ZYDUSLIFE', 'ADANIENT'),
 ('AJANTPHARM', 'ADANIGREEN'),
 ('ALKEM', 'ADANIGREEN'),
 ('APLAPOLLO', 'ADANIGREEN'),
 ('APOLLOHOSP', 'ADANIGREEN'),
 ('ASIANPAINT', 'ADANIGREEN'),
 ('ATGL', 'ADANIGREEN'),
 ('ATUL', 'ADANIGREEN'),
 ('BERGEPAINT', 'ADANIGREEN'),
 ('BORORENEW', 'ADANIGREEN'),
 ('CIPLA', 'ADANIGREEN'),
 ('COFORGE', 'ADANIGREEN'),
 ('CRISIL', 'ADANIGREEN'),
 ('DABUR', 'ADANIGREEN'),
 ('DEEPAKFERT', 'ADANIGREEN'),
 ('DMART', 'ADANIGREEN'),
 ('ERIS', 'ADANIGREEN'),
 ('FACT', 'ADANIGREEN'),
 ('FINEORG', 'ADANIGREEN'),
 ('GMRINFRA', 'ADANIGREEN'),
 ('GUJGASLTD', 'ADANIGREEN'),
 ('HCLTECH', 'ADANIGREEN'),
 ('INDIACEM', 'ADANIGREEN'),
 ('INDIAMART', 'ADANIGREEN'),
 ('INFY', 'ADANIGREEN'),
 ('JBCHEPHARM', 'ADANIGREEN'),
 ('JINDALSTEL', 'ADANIGREEN'),
 ('JSL', 'ADANIGREEN'),
 ('LALPATHLAB', 'ADANIGREEN'),
 ('LAURUSLABS', 'ADANIGREEN'),
 ('MASTEK', 'ADANIGREEN'),
 ('METROPOLIS', 'ADANIGREEN'),
 ('MFSL', 'ADANIGREEN'),
 ('MUTHOOTFIN', 'ADANIGREEN'),
 ('NAUKRI', 'ADANIGREEN'),
 ('NH', 'ADANIGREEN'),
 ('PERSISTENT', 'ADANIGREEN'),
 ('PIDILITIND', 'ADANIGREEN'),
 ('RATNAMANI', 'ADANIGREEN'),
 ('SAREGAMA', 'ADANIGREEN'),
 ('SUPREMEIND', 'ADANIGREEN'),
 ('TCS', 'ADANIGREEN'),
 ('TORNTPOWER', 'ADANIGREEN'),
 ('TRENT', 'ADANIGREEN'),
 ('TRIDENT', 'ADANIGREEN'),
 ('TTML', 'ADANIGREEN'),
 ('VAIBHAVGBL', 'ADANIGREEN'),
 ('ZYDUSLIFE', 'ADANIGREEN'),
 ('ADANIPOWER', 'ADANIPORTS'),
 ('AMBUJACEM', 'ADANIPORTS'),
 ('ASAHIINDIA', 'ADANIPORTS'),
 ('ASHOKLEY', 'ADANIPORTS'),
 ('ASTRAL', 'ADANIPORTS'),
 ('ATGL', 'ADANIPORTS'),
 ('BAJAJFINSV', 'ADANIPORTS'),
 ('BAJFINANCE', 'ADANIPORTS'),
 ('BALRAMCHIN', 'ADANIPORTS'),
 ('BEL', 'ADANIPORTS'),
 ('BHARATFORG', 'ADANIPORTS'),
 ('BLUEDART', 'ADANIPORTS'),
 ('BLUESTARCO', 'ADANIPORTS'),
 ('BRIGADE', 'ADANIPORTS'),
 ('BSE', 'ADANIPORTS'),
 ('CANFINHOME', 'ADANIPORTS'),
 ('CENTURYPLY', 'ADANIPORTS'),
 ('CGPOWER', 'ADANIPORTS'),
 ('CHAMBLFERT', 'ADANIPORTS'),
 ('CIEINDIA', 'ADANIPORTS'),
 ('DLF', 'ADANIPORTS'),
 ('EMAMILTD', 'ADANIPORTS'),
 ('ENDURANCE', 'ADANIPORTS'),
 ('FINCABLES', 'ADANIPORTS'),
 ('FORTIS', 'ADANIPORTS'),
 ('GODREJIND', 'ADANIPORTS'),
 ('GODREJPROP', 'ADANIPORTS'),
 ('GPPL', 'ADANIPORTS'),
 ('HEG', 'ADANIPORTS'),
 ('HINDCOPPER', 'ADANIPORTS'),
 ('HINDZINC', 'ADANIPORTS'),
 ('HUDCO', 'ADANIPORTS'),
 ('ICICIBANK', 'ADANIPORTS'),
 ('IDFCFIRSTB', 'ADANIPORTS'),
 ('IIFL', 'ADANIPORTS'),
 ('INDIGO', 'ADANIPORTS'),
 ('INDUSTOWER', 'ADANIPORTS'),
 ('INOXWIND', 'ADANIPORTS'),
 ('INTELLECT', 'ADANIPORTS'),
 ('JBMA', 'ADANIPORTS'),
 ('JKLAKSHMI', 'ADANIPORTS'),
 ('JKPAPER', 'ADANIPORTS'),
 ('JSWSTEEL', 'ADANIPORTS'),
 ('JUSTDIAL', 'ADANIPORTS'),
 ('KANSAINER', 'ADANIPORTS'),
 ('KEC', 'ADANIPORTS'),
 ('KNRCON', 'ADANIPORTS'),
 ('KPITTECH', 'ADANIPORTS'),
 ('KSB', 'ADANIPORTS'),
 ('LTTS', 'ADANIPORTS'),
 ('MAHABANK', 'ADANIPORTS'),
 ('MARICO', 'ADANIPORTS'),
 ('MMTC', 'ADANIPORTS'),
 ('NCC', 'ADANIPORTS'),
 ('NHPC', 'ADANIPORTS'),
 ('OBEROIRLTY', 'ADANIPORTS'),
 ('PAGEIND', 'ADANIPORTS'),
 ('PCBL', 'ADANIPORTS'),
 ('PFC', 'ADANIPORTS'),
 ('PGHH', 'ADANIPORTS'),
 ('PNCINFRA', 'ADANIPORTS'),
 ('POONAWALLA', 'ADANIPORTS'),
 ('QUESS', 'ADANIPORTS'),
 ('RAMCOCEM', 'ADANIPORTS'),
 ('RCF', 'ADANIPORTS'),
 ('RECLTD', 'ADANIPORTS'),
 ('REDINGTON', 'ADANIPORTS'),
 ('RHIM', 'ADANIPORTS'),
 ('SAIL', 'ADANIPORTS'),
 ('SBIN', 'ADANIPORTS'),
 ('SCHAEFFLER', 'ADANIPORTS'),
 ('SHRIRAMFIN', 'ADANIPORTS'),
 ('SJVN', 'ADANIPORTS'),
 ('SKFINDIA', 'ADANIPORTS'),
 ('SOLARINDS', 'ADANIPORTS'),
 ('SONATSOFTW', 'ADANIPORTS'),
 ('STLTECH', 'ADANIPORTS'),
 ('SUNTV', 'ADANIPORTS'),
 ('TATAINVEST', 'ADANIPORTS'),
 ('TATASTEEL', 'ADANIPORTS'),
 ('TECHM', 'ADANIPORTS'),
 ('TITAN', 'ADANIPORTS'),
 ('TVSMOTOR', 'ADANIPORTS'),
 ('UNOMINDA', 'ADANIPORTS'),
 ('VOLTAS', 'ADANIPORTS'),
 ('WELSPUNLIV', 'ADANIPORTS'),
 ('BAJAJFINSV', 'ADANIPOWER'),
 ('BAJAJHLDNG', 'ADANIPOWER'),
 ('BLUESTARCO', 'ADANIPOWER'),
 ('CARBORUNIV', 'ADANIPOWER'),
 ('CESC', 'ADANIPOWER'),
 ('CHOLAFIN', 'ADANIPOWER'),
 ('CHOLAHLDNG', 'ADANIPOWER'),
 ('CIEINDIA', 'ADANIPOWER'),
 ('CUMMINSIND', 'ADANIPOWER'),
 ('DCMSHRIRAM', 'ADANIPOWER'),
 ('ELECON', 'ADANIPOWER'),
 ('ELGIEQUIP', 'ADANIPOWER'),
 ('GAIL', 'ADANIPOWER'),
 ('GESHIP', 'ADANIPOWER'),
 ('GODREJIND', 'ADANIPOWER'),
 ('GRAPHITE', 'ADANIPOWER'),
 ('GRINDWELL', 'ADANIPOWER'),
 ('HFCL', 'ADANIPOWER'),
 ('HINDALCO', 'ADANIPOWER'),
 ('HINDPETRO', 'ADANIPOWER'),
 ('ICICIBANK', 'ADANIPOWER'),
 ('IDFC', 'ADANIPOWER'),
 ('IDFCFIRSTB', 'ADANIPOWER'),
 ('IIFL', 'ADANIPOWER'),
 ('JINDALSAW', 'ADANIPOWER'),
 ('JKPAPER', 'ADANIPOWER'),
 ('JSWENERGY', 'ADANIPOWER'),
 ('JUSTDIAL', 'ADANIPOWER'),
 ('LT', 'ADANIPOWER'),
 ('MHRIL', 'ADANIPOWER'),
 ('MINDACORP', 'ADANIPOWER'),
 ('NHPC', 'ADANIPOWER'),
 ('NMDC', 'ADANIPOWER'),
 ('OBEROIRLTY', 'ADANIPOWER'),
 ('OIL', 'ADANIPOWER'),
 ('ONGC', 'ADANIPOWER'),
 ('PEL', 'ADANIPOWER'),
 ('PGHH', 'ADANIPOWER'),
 ('PNCINFRA', 'ADANIPOWER'),
 ('POWERGRID', 'ADANIPOWER'),
 ('PRSMJOHNSN', 'ADANIPOWER'),
 ('QUESS', 'ADANIPOWER'),
 ('RECLTD', 'ADANIPOWER'),
 ('RVNL', 'ADANIPOWER'),
 ('SCHAEFFLER', 'ADANIPOWER'),
 ('SHRIRAMFIN', 'ADANIPOWER'),
 ('SOBHA', 'ADANIPOWER'),
 ('SOLARINDS', 'ADANIPOWER'),
 ('SUNDRMFAST', 'ADANIPOWER'),
 ('TATAMTRDVR', 'ADANIPOWER'),
 ('TATAPOWER', 'ADANIPOWER'),
 ('UBL', 'ADANIPOWER'),
 ('USHAMART', 'ADANIPOWER'),
 ('VGUARD', 'ADANIPOWER'),
 ('VTL', 'ADANIPOWER'),
 ('ALLCARGO', 'AIAENG'),
 ('BERGEPAINT', 'AIAENG'),
 ('CROMPTON', 'AIAENG'),
 ('EICHERMOT', 'AIAENG'),
 ('GAEL', 'AIAENG'),
 ('GPIL', 'AIAENG'),
 ('JSWSTEEL', 'AIAENG'),
 ('ALLCARGO', 'AJANTPHARM'),
 ('AMBUJACEM', 'AJANTPHARM'),
 ('CGCL', 'AJANTPHARM'),
 ('COROMANDEL', 'AJANTPHARM'),
 ('CRISIL', 'AJANTPHARM'),
 ('CROMPTON', 'AJANTPHARM'),
 ('ECLERX', 'AJANTPHARM'),
 ('ESCORTS', 'AJANTPHARM'),
 ('FINEORG', 'AJANTPHARM'),
 ('FSL', 'AJANTPHARM'),
 ('GAEL', 'AJANTPHARM'),
 ('GMRINFRA', 'AJANTPHARM'),
 ('GPIL', 'AJANTPHARM'),
 ('HAL', 'AJANTPHARM'),
 ('HINDUNILVR', 'AJANTPHARM'),
 ('HONAUT', 'AJANTPHARM'),
 ('INDIAMART', 'AJANTPHARM'),
 ('INFY', 'AJANTPHARM'),
 ('IPCALAB', 'AJANTPHARM'),
 ('JINDALSTEL', 'AJANTPHARM'),
 ('MASTEK', 'AJANTPHARM'),
 ('MPHASIS', 'AJANTPHARM'),
 ('NESTLEIND', 'AJANTPHARM'),
 ('NETWORK18', 'AJANTPHARM'),
 ('RATNAMANI', 'AJANTPHARM'),
 ('SAREGAMA', 'AJANTPHARM'),
 ('SUPREMEIND', 'AJANTPHARM'),
 ('SYNGENE', 'AJANTPHARM'),
 ('TCS', 'AJANTPHARM'),
 ('TIINDIA', 'AJANTPHARM'),
 ('TRENT', 'AJANTPHARM'),
 ('TRIDENT', 'AJANTPHARM'),
 ('TTML', 'AJANTPHARM'),
 ('VBL', 'AJANTPHARM'),
 ('WIPRO', 'AJANTPHARM'),
 ('ALLCARGO', 'ALKEM'),
 ('AMBER', 'ALKEM'),
 ('APLAPOLLO', 'ALKEM'),
 ('APOLLOHOSP', 'ALKEM'),
 ('BORORENEW', 'ALKEM'),
 ('CGCL', 'ALKEM'),
 ('CIPLA', 'ALKEM'),
 ('COROMANDEL', 'ALKEM'),
 ('CRISIL', 'ALKEM'),
 ('CROMPTON', 'ALKEM'),
 ('ECLERX', 'ALKEM'),
 ('ESCORTS', 'ALKEM'),
 ('FACT', 'ALKEM'),
 ('GAEL', 'ALKEM'),
 ('GMRINFRA', 'ALKEM'),
 ('GPIL', 'ALKEM'),
 ('HAL', 'ALKEM'),
 ('HCLTECH', 'ALKEM'),
 ('HINDUNILVR', 'ALKEM'),
 ('INDIACEM', 'ALKEM'),
 ('INDIAMART', 'ALKEM'),
 ('INFY', 'ALKEM'),
 ('IPCALAB', 'ALKEM'),
 ('ISEC', 'ALKEM'),
 ('JINDALSTEL', 'ALKEM'),
 ('JSL', 'ALKEM'),
 ('LINDEINDIA', 'ALKEM'),
 ('MASTEK', 'ALKEM'),
 ('PERSISTENT', 'ALKEM'),
 ('PIDILITIND', 'ALKEM'),
 ('RATNAMANI', 'ALKEM'),
 ('RELIANCE', 'ALKEM'),
 ('SPARC', 'ALKEM'),
 ('SUPREMEIND', 'ALKEM'),
 ('SYNGENE', 'ALKEM'),
 ('TANLA', 'ALKEM'),
 ('TATACHEM', 'ALKEM'),
 ('TCS', 'ALKEM'),
 ('TIINDIA', 'ALKEM'),
 ('TORNTPOWER', 'ALKEM'),
 ('TRENT', 'ALKEM'),
 ('TRIDENT', 'ALKEM'),
 ('VBL', 'ALKEM'),
 ('ALLCARGO', 'ALKYLAMINE'),
 ('AMBUJACEM', 'ALKYLAMINE'),
 ('APOLLOHOSP', 'ALKYLAMINE'),
 ('ATGL', 'ALKYLAMINE'),
 ('BIRLACORPN', 'ALKYLAMINE'),
 ('CGCL', 'ALKYLAMINE'),
 ('CROMPTON', 'ALKYLAMINE'),
 ('ECLERX', 'ALKYLAMINE'),
 ('EMAMILTD', 'ALKYLAMINE'),
 ('FDC', 'ALKYLAMINE'),
 ('FSL', 'ALKYLAMINE'),
 ('GLENMARK', 'ALKYLAMINE'),
 ('GMRINFRA', 'ALKYLAMINE'),
 ('GPPL', 'ALKYLAMINE'),
 ('HAL', 'ALKYLAMINE'),
 ('HINDUNILVR', 'ALKYLAMINE'),
 ('HINDZINC', 'ALKYLAMINE'),
 ('HONAUT', 'ALKYLAMINE'),
 ('INFY', 'ALKYLAMINE'),
 ('IPCALAB', 'ALKYLAMINE'),
 ('JBMA', 'ALKYLAMINE'),
 ('JSWSTEEL', 'ALKYLAMINE'),
 ('MPHASIS', 'ALKYLAMINE'),
 ('NATCOPHARM', 'ALKYLAMINE'),
 ('NESTLEIND', 'ALKYLAMINE'),
 ('NETWORK18', 'ALKYLAMINE'),
 ('PCBL', 'ALKYLAMINE'),
 ('POLYCAB', 'ALKYLAMINE'),
 ('REDINGTON', 'ALKYLAMINE'),
 ('RENUKA', 'ALKYLAMINE'),
 ('SAREGAMA', 'ALKYLAMINE'),
 ('SHREECEM', 'ALKYLAMINE'),
 ('SUPREMEIND', 'ALKYLAMINE'),
 ('SYNGENE', 'ALKYLAMINE'),
 ('TCS', 'ALKYLAMINE'),
 ('TRIDENT', 'ALKYLAMINE'),
 ('TTML', 'ALKYLAMINE'),
 ('VBL', 'ALKYLAMINE'),
 ('WIPRO', 'ALKYLAMINE'),
 ('AMBER', 'ALLCARGO'),
 ('BALKRISIND', 'ALLCARGO'),

In [85]:
len(pairs_list)

10076